fix for hosting

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -1,80 +1,80 @@
-# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
-# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
+# # This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
+# # For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
 
-name: Node.js CI
+# name: Node.js CI
 
-on:
-  push:
-    branches: [main]
-  pull_request:
-    branches: [main]
-  workflow_dispatch:
+# on:
+#   push:
+#     branches: [main]
+#   pull_request:
+#     branches: [main]
+#   workflow_dispatch:
 
-jobs:
-  lint:
-    runs-on: ${{ matrix.os }}
-    timeout-minutes: 5
-    strategy:
-      matrix:
-        os: [ubuntu-latest, windows-latest, macos-latest]
-    steps:
-      - uses: actions/checkout@v4
-      - uses: actions/setup-node@v3
-        with:
-          node-version-file: ".nvmrc"
-          cache: "npm"
-      - run: npm ci
-      - name: Lint
-        run: npm run lint
+# jobs:
+#   lint:
+#     runs-on: ${{ matrix.os }}
+#     timeout-minutes: 5
+#     strategy:
+#       matrix:
+#         os: [ubuntu-latest, windows-latest, macos-latest]
+#     steps:
+#       - uses: actions/checkout@v4
+#       - uses: actions/setup-node@v3
+#         with:
+#           node-version-file: ".nvmrc"
+#           cache: "npm"
+#       - run: npm ci
+#       - name: Lint
+#         run: npm run lint
 
-  build:
-    runs-on: ${{ matrix.os }}
-    timeout-minutes: 10
-    strategy:
-      matrix:
-        node-version: [16.x, 18.x, 20.x]
-        os: [ubuntu-20.04, windows-latest, macos-latest]
-        exclude:
-          - os: windows-latest
-            node-version: 16.x
-          - os: windows-latest
-            node-version: 18.x
-          - os: macos-latest
-            node-version: 16.x
-          - os: macos-latest
-            node-version: 18.x
-    steps:
-      - uses: actions/checkout@v4
-      - name: Use Node.js ${{ matrix.node-version }}
-        uses: actions/setup-node@v3
-        with:
-          node-version: ${{ matrix.node-version }}
-          cache: "npm"
-      - run: npm ci
-      - name: Build and Statically Render
-        shell: bash
-        run: |
-          function retry {
-            local n=1
-            local max=5
-            local delay=1
-            while true; do
-              "$@" && break || {
-                if [[ $n -lt $max ]]; then
-                  ((n++))
-                  echo "Command failed. Attempt $n/$max:"
-                  sleep $delay;
-                else
-                  echo "The command has failed after $n attempts."
-                  return 1
-                fi
-              }
-            done
-          }
-          retry npm run predeploy
-        env:
-          NODE_ENV: development
-      - name: Test
-        run: npm test
-        env:
-          NODE_ENV: development
+#   build:
+#     runs-on: ${{ matrix.os }}
+#     timeout-minutes: 10
+#     strategy:
+#       matrix:
+#         node-version: [16.x, 18.x, 20.x]
+#         os: [ubuntu-20.04, windows-latest, macos-latest]
+#         exclude:
+#           - os: windows-latest
+#             node-version: 16.x
+#           - os: windows-latest
+#             node-version: 18.x
+#           - os: macos-latest
+#             node-version: 16.x
+#           - os: macos-latest
+#             node-version: 18.x
+#     steps:
+#       - uses: actions/checkout@v4
+#       - name: Use Node.js ${{ matrix.node-version }}
+#         uses: actions/setup-node@v3
+#         with:
+#           node-version: ${{ matrix.node-version }}
+#           cache: "npm"
+#       - run: npm ci
+#       - name: Build and Statically Render
+#         shell: bash
+#         run: |
+#           function retry {
+#             local n=1
+#             local max=5
+#             local delay=1
+#             while true; do
+#               "$@" && break || {
+#                 if [[ $n -lt $max ]]; then
+#                   ((n++))
+#                   echo "Command failed. Attempt $n/$max:"
+#                   sleep $delay;
+#                 else
+#                   echo "The command has failed after $n attempts."
+#                   return 1
+#                 fi
+#               }
+#             done
+#           }
+#           retry npm run predeploy
+#         env:
+#           NODE_ENV: development
+#       - name: Test
+#         run: npm test
+#         env:
+#           NODE_ENV: development
